version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: healthsense-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: healthsense
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sa-network

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sa-network

volumes:
  db_data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  sa-network:
    name: sa-network
